#pragma once

namespace tenryu::diagnostics {

enum class RadialFourierAuditV2Mode {
  Off,
  Stub,
  DummyBuffer,
  Full,
};

}  // namespace tenryu::diagnostics

#if defined(TENRYU_RFA_V2_MODE_OFF)
#define TENRYU_RFA_V2_MODE_IS_OFF 1
#define TENRYU_RFA_V2_MODE_IS_STUB 0
#define TENRYU_RFA_V2_MODE_IS_DUMMY_BUFFER 0
#define TENRYU_RFA_V2_MODE_IS_FULL 0
#elif defined(TENRYU_RFA_V2_MODE_STUB)
#define TENRYU_RFA_V2_MODE_IS_OFF 0
#define TENRYU_RFA_V2_MODE_IS_STUB 1
#define TENRYU_RFA_V2_MODE_IS_DUMMY_BUFFER 0
#define TENRYU_RFA_V2_MODE_IS_FULL 0
#elif defined(TENRYU_RFA_V2_MODE_DUMMY_BUFFER)
#define TENRYU_RFA_V2_MODE_IS_OFF 0
#define TENRYU_RFA_V2_MODE_IS_STUB 0
#define TENRYU_RFA_V2_MODE_IS_DUMMY_BUFFER 1
#define TENRYU_RFA_V2_MODE_IS_FULL 0
#elif defined(TENRYU_RFA_V2_MODE_FULL)
#define TENRYU_RFA_V2_MODE_IS_OFF 0
#define TENRYU_RFA_V2_MODE_IS_STUB 0
#define TENRYU_RFA_V2_MODE_IS_DUMMY_BUFFER 0
#define TENRYU_RFA_V2_MODE_IS_FULL 1
#else
#define TENRYU_RFA_V2_MODE_IS_OFF 0
#define TENRYU_RFA_V2_MODE_IS_STUB 0
#define TENRYU_RFA_V2_MODE_IS_DUMMY_BUFFER 0
#define TENRYU_RFA_V2_MODE_IS_FULL 1
#endif

#define TENRYU_RFA_V2_COMPILED (!TENRYU_RFA_V2_MODE_IS_OFF)
#define TENRYU_RFA_V2_KERNEL_LAUNCHES \
  (TENRYU_RFA_V2_MODE_IS_DUMMY_BUFFER || TENRYU_RFA_V2_MODE_IS_FULL)
#define TENRYU_RFA_V2_CAPTURES_COEFFS TENRYU_RFA_V2_MODE_IS_FULL
#define TENRYU_RFA_V2_WRITES_HISTORY TENRYU_RFA_V2_MODE_IS_FULL
