// 1D presets of TENRYU Studio. Each one was run to its end time and checked against its physics
// (docs/beta/CHANGELOG.md, gui/manual §3). The meshes come from the 1D mesh skill
// (tenryu-mesh-1d): laser-driven presets carry the mesh that tools/assist recommend-mesh made and
// validated with a solver binary (presetMeshes.ts, regenerated by scripts/make_preset_meshes.sh);
// presets driven by a radiation temperature or a pressure, which the recommender does not cover,
// use a per-layer table built by the skill's rules (finest cells where the drive enters, widths
// continuous across material interfaces) and checked with a convergence pair.
import {
  defaultFormState,
  makeHotEChannel,
  type FormState,
  type MaterialForm,
  type RegionForm,
} from "./deck/formState";
import { defaultLayerZoning, type LayerZoningForm } from "./deck/mesh1d";
import { applyRecommendation, parseRecommendation } from "./deck/meshRecommend";
import { PRESET_MESHES, type PresetMeshId } from "./presetMeshes";
import { q } from "./units";

const um = (value: number) => q(value, "µm");

function idealMaterial(name: string, A: number, Z: number, kappaA = 0, cvEOverride?: number): MaterialForm {
  return {
    name,
    A,
    Z,
    eosModel: "ideal_gas",
    gamma: 5 / 3,
    cvEOverride,
    eosFile: "",
    opacityModel: "constant",
    kappaA,
    kappaS: 0,
    opacityFile: "",
  };
}

/** A material on a TMAT-H5 table of the repository (TMAT-H5/<file>, not in the beta distribution). */
function tableMaterial(name: string, A: number, Z: number, file: string, tableOpacity: boolean): MaterialForm {
  return {
    name,
    A,
    Z,
    eosModel: "tmat",
    gamma: 5 / 3,
    cvEOverride: undefined,
    eosFile: file,
    opacityModel: tableOpacity ? "tmat" : "constant",
    kappaA: 0,
    kappaS: 0,
    opacityFile: tableOpacity ? file : "",
  };
}

function region(materialName: string, rOuterUm: number, rho: number, temperatureEV: number): RegionForm {
  return {
    materialName,
    rOuter: um(rOuterUm),
    rho,
    Te: q(temperatureEV, "eV"),
    Ti: q(temperatureEV, "eV"),
  };
}

function layer(change: Partial<LayerZoningForm>): LayerZoningForm {
  return { ...defaultLayerZoning(), ...change };
}

/** Laser drive with the example suite's conventions: a ghost corona outside the bare surface,
 *  deposit smoothing, a single reference beam (f/3, centre focus) and the implicit conduction
 *  solver (SKILL tenryu-namelist §3; the mesh-convergence campaign behind recommend-mesh). */
function laserDrive(f: FormState, wavelengthNm: number, mode: FormState["laser"]["mode"]): void {
  f.laser.enabled = true;
  f.laser.wavelengthNm = wavelengthNm;
  f.laser.mode = mode;
  f.laser.raysPerBeam = 1000;
  f.laser.ghostCorona.enabled = true;
  f.laser.depositSmoothPasses = 3;
  f.laser.depositSmoothAlpha = 0.25;
  f.laser.beams[0] = { ...f.laser.beams[0], fNumber: 3.0, focusZUm: 0, w0Um: 250, superGaussianM: 4 };
  f.geometry.vacuumOutside1d = true;
  f.geometry.coronaRamp1d.enabled = false;
  f.conduction.enabled = true;
  f.conduction.solver = "implicit";
  f.conduction.fLim = 0.06;
}

/** Square pulse with linear rise and fall (W per cm² for planar targets, total W for spheres). */
function trapezoid(f: FormState, powerTW: number, flatNs: number, riseNs: number, fallNs: number): void {
  f.laser.waveformMode = "square";
  f.laser.powerW = q(powerTW, "TW");
  f.laser.pulseDuration = q(flatNs, "ns");
  f.laser.riseTime = q(riseNs, "ns");
  f.laser.fallTime = q(fallNs, "ns");
}

/** The recommended mesh stored for this preset (made for exactly these conditions). */
function recommendedMesh(f: FormState, id: PresetMeshId): void {
  const stored = PRESET_MESHES[id];
  if (stored === undefined) {
    // Not generated yet (scripts/make_preset_meshes.sh): a coarse placeholder.
    f.mesh.grid1d = "uniform";
    f.mesh.nr = 200;
    return;
  }
  applyRecommendation(f, parseRecommendation(JSON.stringify(stored.payload)), stored.conditionsKey, stored.binary, stored.createdAt);
}

function common(f: FormState, name: string, geometry: FormState["main"]["geometry1d"], tEndNs: number): void {
  f.main.name = name;
  f.main.dimension = "1D_SPH";
  f.main.geometry1d = geometry;
  f.main.tEnd = q(tEndNs, "ns");
  f.main.maxSteps = 10_000_000;
  f.mesh.rMin = q(0, "cm");
  f.radiation.enabled = false;
}

// ---------------------------------------------------------------------------------------------
// Basic

export function presetBlank(): FormState {
  return defaultFormState();
}

/** Planar CH foil on a rigid rear wall (the mid-plane of a foil twice as thick driven from both
 *  sides), 351 nm at 1e14 W/cm² for 1 ns; ideal-gas CH, no radiation. */
export function presetLaserFoil(): FormState {
  const f = defaultFormState();
  common(f, "laser_foil", "planar", 1.5);
  f.mesh.rMax = um(125);
  f.materials = [idealMaterial("CH", 6.5, 3.5)];
  f.geometry.regions = [region("CH", 25, 1.05, 0.025)];
  laserDrive(f, 351, "radial_absorption_1d");
  trapezoid(f, 100, 1.0, 0.1, 0.1);
  f.output.plotEveryS = q(20, "ps");
  recommendedMesh(f, "laserFoil");
  return f;
}

/** GXII-class direct-drive implosion: 7 µm CD shell (250 µm outer radius) on D2 gas, 527 nm
 *  Gaussian of 3e14 W/cm² peak (1 ns FWHM), ray tracing; ideal gas, no radiation. */
export function presetLaserShell(): FormState {
  const f = defaultFormState();
  common(f, "laser_shell_implosion", "spherical", 2.4);
  f.mesh.rMax = um(400);
  f.materials = [idealMaterial("D2", 2.01, 1.0), idealMaterial("CD", 7.0, 3.5)];
  f.geometry.regions = [region("D2", 243, 0.02, 0.025), region("CD", 250, 1.05, 0.025)];
  laserDrive(f, 527, "raytrace_2d");
  f.laser.waveformMode = "gaussian";
  f.laser.gaussianSpec = "peak";
  // 3e14 W/cm² over the target surface 4 pi (250 µm)^2.
  f.laser.gaussianPeakW = q((3.0e14 * 4 * Math.PI * 0.025 * 0.025) / 1.0e12, "TW");
  f.laser.gaussianFwhm = q(1.0, "ns");
  f.laser.gaussianCenter = q(1.2, "ns");
  f.output.plotEveryS = q(20, "ps");
  recommendedMesh(f, "laserShell");
  return f;
}

/** Marshak (radiation heat) wave into a static slab: gray FLD, 120 eV boundary, no hydro and no
 *  conduction; 1T with a fixed electron heat capacity. */
export function presetMarshakWave(): FormState {
  const f = defaultFormState();
  common(f, "marshak_wave", "planar", 1.0);
  f.main.temperatureModel = "1T";
  f.mesh.rMax = um(100);
  f.materials = [idealMaterial("CH", 6.5, 3.5, 2000.0, 3.0e11)];
  f.geometry.regions = [region("CH", 100, 0.2, 1.0)];
  f.geometry.radiationField = "zero";
  f.radiation.enabled = true;
  f.radiation.mode = "multigroup_diffusion";
  f.radiation.outerR = "marshak";
  f.radiation.marshakMode = "constant";
  f.radiation.marshakTrEV = 120.0;
  f.hydro.enabled = false;
  f.conduction.enabled = false;
  f.numerics.floors.TeFloorEV = 1.0;
  f.numerics.floors.TiFloorEV = 1.0;
  f.output.plotEveryS = q(20, "ps");
  // Finest cells (0.1 µm) where the radiation enters; 0.2 µm at the 1 ns front (~35 µm deep).
  f.mesh.grid1d = "layers";
  f.mesh.layerZoning = [layer({ cells: 300, spacing: "ratio", ratioSpec: "first_width", firstWidthCm: 0.1e-4, fineSide: "outer" })];
  return f;
}

/** Indirect-drive capsule: CH ablator on DT gas driven by a hohlraum radiation temperature Tr(t)
 *  (120 eV foot, 200 eV main) through the outer Marshak boundary; gray FLD, 2T. */
export function presetIndirectCapsule(): FormState {
  const f = defaultFormState();
  common(f, "indirect_drive_capsule", "spherical", 3.0);
  f.mesh.rMax = um(330);
  f.materials = [idealMaterial("DT", 2.5, 1.0, 1.0), idealMaterial("CH", 6.5, 3.5, 2000.0)];
  f.geometry.regions = [region("DT", 300, 0.01, 1e-3), region("CH", 330, 1.05, 1e-3)];
  f.geometry.radiationField = "zero";
  f.radiation.enabled = true;
  f.radiation.mode = "multigroup_diffusion";
  f.radiation.outerR = "marshak";
  f.radiation.marshakMode = "table";
  // The drive ends just after stagnation (2.4 ns). Held longer, the outermost cells of the blow-off
  // (at the density floor) keep accelerating under the outer Marshak boundary without bound
  // (5e9 cm/s at 2.45 ns, above 1e15 cm/s by 5 ns in the 2026-10-01 verification runs).
  f.radiation.marshakPoints = [
    { t: 0, v: 120 },
    { t: 0.5, v: 120 },
    { t: 1.0, v: 200 },
    { t: 2.4, v: 200 },
    { t: 2.6, v: 1 },
    { t: 3.0, v: 1 },
  ];
  f.conduction.enabled = true;
  f.conduction.solver = "implicit";
  f.numerics.dtInitial = q(1e-15, "s");
  f.numerics.floors.TeFloorEV = 1e-3;
  f.numerics.floors.TiFloorEV = 1e-3;
  f.output.plotEveryS = q(50, "ps");
  // Ablator: finest cells at both faces (ablation front outside, hot-spot boundary inside);
  // gas: the same width at the interface, coarsening toward the centre.
  f.mesh.grid1d = "layers";
  f.mesh.layerZoning = [
    layer({ cells: 150, spacing: "ratio", ratioSpec: "first_width", firstWidthCm: 0.05e-4, fineSide: "outer" }),
    layer({ cells: 120, spacing: "ratio", ratioSpec: "first_width", firstWidthCm: 0.05e-4, fineSide: "both" }),
  ];
  return f;
}

// ---------------------------------------------------------------------------------------------
// Optional kernels

/** Radiation-driven planar foil with discrete-ordinates (S_N, 16 directions) transport in four
 *  gray groups: a 150 eV drive through the outer boundary; 2T hydro with implicit conduction. */
export function presetSnRadiationFoil(): FormState {
  const f = defaultFormState();
  common(f, "sn_radiation_foil", "planar", 2.0);
  f.mesh.rMax = um(40);
  f.materials = [idealMaterial("CH", 6.5, 3.5, 2000.0)];
  f.geometry.regions = [region("CH", 40, 1.05, 0.025)];
  f.geometry.radiationField = "zero";
  f.radiation.enabled = true;
  f.radiation.mode = "sn_transport";
  f.radiation.snNAngles = 16;
  f.radiation.groups = 4;
  f.radiation.groupBoundsEV = [1, 100, 300, 1000, 10000];
  f.radiation.outerR = "marshak";
  f.radiation.marshakMode = "table";
  f.radiation.marshakPoints = [
    { t: 0, v: 10 },
    { t: 0.1, v: 150 },
    { t: 2.0, v: 150 },
  ];
  f.conduction.enabled = true;
  f.conduction.solver = "implicit";
  f.numerics.floors.TeFloorEV = 1e-3;
  f.numerics.floors.TiFloorEV = 1e-3;
  f.output.plotEveryS = q(20, "ps");
  f.mesh.grid1d = "layers";
  f.mesh.layerZoning = [layer({ cells: 200, spacing: "ratio", ratioSpec: "first_width", firstWidthCm: 0.05e-4, fineSide: "outer" })];
  return f;
}

/** Planar CH foil at 5e14 W/cm² (351 nm) with nonlocal electron transport (SNB). */
export function presetSnbFoil(): FormState {
  const f = defaultFormState();
  common(f, "snb_nonlocal_foil", "planar", 1.2);
  f.mesh.rMax = um(125);
  f.materials = [idealMaterial("CH", 6.5, 3.5)];
  f.geometry.regions = [region("CH", 25, 1.05, 0.025)];
  laserDrive(f, 351, "radial_absorption_1d");
  trapezoid(f, 500, 1.0, 0.1, 0.1);
  // The SNB correction runs on the explicit super-time-stepping solve (the solver refuses it with
  // the implicit one).
  f.conduction.nonlocalModel = "snb";
  f.conduction.solver = "sts";
  f.conduction.fLim = 0.5;
  f.output.plotEveryS = q(20, "ps");
  recommendedMesh(f, "snbFoil");
  return f;
}

/** Direct-drive shell with cross-beam energy transfer among the 12 GXII ports and hot electrons
 *  from two-plasmon decay and stimulated Raman scattering (threshold model), 351 nm at 5e14 W/cm²
 *  for 1 ns. CBET traces every ray on the slower path and costs a fixed amount per step on top of
 *  ray tracing, so the preset uses 200 rays per beam and stops after the pulse (1.2 ns). */
export function presetCbetHotElectrons(): FormState {
  const f = defaultFormState();
  common(f, "cbet_hot_electrons", "spherical", 1.2);
  f.mesh.rMax = um(400);
  f.materials = [idealMaterial("D2", 2.01, 1.0), idealMaterial("CD", 7.0, 3.5)];
  f.geometry.regions = [region("D2", 230, 0.0025, 0.025), region("CD", 250, 1.05, 0.025)];
  laserDrive(f, 351, "raytrace_2d");
  f.laser.raysPerBeam = 200;
  // 5e14 W/cm² over 4 pi (250 µm)^2.
  trapezoid(f, (5.0e14 * 4 * Math.PI * 0.025 * 0.025) / 1.0e12, 1.0, 0.1, 0.1);
  f.laser.cbet.enabled = true;
  f.laser.cbet.portPreset = "gxii";
  f.laser.hotE.enabled = true;
  f.laser.hotE.useChannels = true;
  f.laser.hotE.etaEvolution = "model";
  f.laser.hotE.subtractFromLaser = true;
  f.laser.hotE.channels = [makeHotEChannel("tpd"), makeHotEChannel("srs")];
  f.output.plotEveryS = q(20, "ps");
  recommendedMesh(f, "cbetHotElectrons");
  return f;
}

/** Radiation-driven DT exploding pusher with fusion burn (Fraley), ion plasma viscosity
 *  (Braginskii) and ion heat conduction: a 10 µm CD shell on 0.004 g/cc DT driven by a stepped
 *  Tr(t); eight gray groups. */
export function presetBurnPusher(): FormState {
  const f = defaultFormState();
  common(f, "burn_exploding_pusher", "spherical", 4.0);
  f.mesh.rMax = um(360);
  f.materials = [idealMaterial("DT", 2.5, 1.0, 1.0), idealMaterial("CD", 7.0, 3.5, 5000.0)];
  f.geometry.regions = [region("DT", 350, 0.004, 0.025), region("CD", 360, 1.05, 0.025)];
  f.geometry.radiationField = "zero";
  f.radiation.enabled = true;
  f.radiation.mode = "multigroup_diffusion";
  f.radiation.groups = 8;
  f.radiation.groupBoundsEV = [1, 3, 10, 30, 100, 300, 1000, 3000, 10000];
  f.radiation.outerR = "marshak";
  f.radiation.marshakMode = "table";
  f.radiation.marshakPoints = [
    { t: 0, v: 1 },
    { t: 0.2, v: 60 },
    { t: 0.8, v: 60 },
    { t: 1.0, v: 120 },
    { t: 1.8, v: 120 },
    { t: 2.2, v: 180 },
    { t: 3.2, v: 180 },
    { t: 3.5, v: 1 },
    { t: 4.0, v: 1 },
  ];
  f.conduction.enabled = true;
  f.conduction.solver = "implicit";
  f.conduction.ionConduction = true;
  f.hydro.plasmaVisc.enabled = true;
  f.hydro.plasmaVisc.model = "braginskii";
  f.hydro.plasmaVisc.species = "ion";
  f.burn.enabled = true;
  f.burn.fuels = { DT: true, DD: false, D3He: false };
  f.burn.scheme = "fraley";
  f.burn.partition = "fraley";
  f.burn.fuelMaterials = "DT";
  f.burn.xD = 0.5;
  f.burn.xT = 0.5;
  f.burn.xHe3 = 0;
  f.numerics.floors.TeFloorEV = 1e-3;
  f.numerics.floors.TiFloorEV = 1e-3;
  f.output.plotEveryS = q(50, "ps");
  f.mesh.grid1d = "layers";
  f.mesh.layerZoning = [
    layer({ cells: 150, spacing: "ratio", ratioSpec: "first_width", firstWidthCm: 0.1e-4, fineSide: "outer" }),
    layer({ cells: 60, spacing: "ratio", ratioSpec: "first_width", firstWidthCm: 0.05e-4, fineSide: "both" }),
  ];
  return f;
}

/** Group bounds of the TMAT-H5 tables of the repository (80 groups, 0.1 eV to 300 keV). */
const TABLE_GROUP_BOUNDS_EV = [
  0.1, 0.1204936, 0.1451871, 0.1749412, 0.2107929, 0.253992, 0.3060442, 0.3687637, 0.4443366, 0.5353973, 0.6451195,
  0.7773278, 0.9366303, 1.12858, 1.359866, 1.638552, 1.97435, 2.378966, 2.866502, 3.453952, 4.161791, 5.014693,
  6.042384, 7.280687, 8.772763, 10.57062, 12.73692, 15.34717, 18.49236, 22.28212, 26.84853, 32.35076, 38.9806,
  46.96913, 56.5948, 68.19312, 82.16835, 99.00761, 119.2978, 143.7463, 173.2051, 208.7011, 251.4714, 303.007,
  365.1041, 439.9271, 530.084, 638.7174, 769.6136, 927.3352, 1117.38, 1346.371, 1622.291, 1954.757, 2355.358,
  2838.055, 3419.675, 4120.49, 4964.927, 5982.42, 7208.434, 8685.703, 10465.72, 12610.52, 15194.87, 18308.85,
  22060.99, 26582.09, 32029.71, 38593.76, 46503.01, 56033.16, 67516.38, 81352.92, 98025.07, 118113.9, 142319.8,
  171486.2, 206629.9, 248975.9, 300000.0,
];

/** Planar CD foil on the CD table (EOS and 80-group opacity) with multigroup flux-limited
 *  diffusion, 351 nm at 1e14 W/cm²; needs TMAT-H5/CD.tmat.h5 on the server. */
export function presetTableRadiationFoil(): FormState {
  const f = defaultFormState();
  common(f, "table_radiation_foil", "planar", 1.5);
  f.mesh.rMax = um(125);
  f.materials = [tableMaterial("CD", 7.0, 3.5, "TMAT-H5/CD.tmat.h5", true)];
  f.geometry.regions = [region("CD", 25, 1.05, 1.0)];
  f.geometry.radiationField = "zero";
  f.radiation.enabled = true;
  f.radiation.mode = "multigroup_diffusion";
  f.radiation.groups = 80;
  f.radiation.groupBoundsEV = [...TABLE_GROUP_BOUNDS_EV];
  f.radiation.outerR = "vacuum";
  laserDrive(f, 351, "radial_absorption_1d");
  trapezoid(f, 100, 1.0, 0.1, 0.1);
  f.numerics.floors.TeFloorEV = 0.1;
  f.numerics.floors.TiFloorEV = 0.1;
  f.output.plotEveryS = q(20, "ps");
  recommendedMesh(f, "tableRadiationFoil");
  return f;
}

/** Planar CD ablator on liquid D2 on the TMAT tables, both held in mechanical equilibrium at their
 *  initial state by the cold-equilibrium constitutive branch until heated (no motion before the
 *  shock arrives); 351 nm at 1e14 W/cm². Needs TMAT-H5/CD.tmat.h5 and TMAT-H5/D2.tmat.h5. */
export function presetColdEquilibriumLayers(): FormState {
  const f = defaultFormState();
  common(f, "cold_equilibrium_layers", "planar", 1.5);
  f.mesh.rMax = um(175);
  f.materials = [
    tableMaterial("D2", 2.01, 1.0, "TMAT-H5/D2.tmat.h5", false),
    tableMaterial("CD", 7.0, 3.5, "TMAT-H5/CD.tmat.h5", false),
  ];
  f.geometry.regions = [region("D2", 50, 0.17, 0.1), region("CD", 75, 1.05, 0.1)];
  laserDrive(f, 351, "radial_absorption_1d");
  trapezoid(f, 100, 1.0, 0.1, 0.1);
  f.hydro.inactiveCells = "cold_equilibrium";
  f.hydro.tStartEV = 2.0;
  f.hydro.qeiHeatCapacity = "table";
  // Reference states: the initial density and temperature, zero pressure, and the measured bulk
  // moduli of liquid D2 (1.2e9 dyn/cm², Richardson et al. 2014) and polystyrene (5.8e10 dyn/cm²,
  // Topp & Cahill 1996), the values the cold-equilibrium design records.
  f.materials[0].coldReference = { rhoGcc: 0.17, Te0: q(0.1, "eV"), Ti0: q(0.1, "eV"), P0: q(0, "GPa"), K0: q(0.12, "GPa") };
  f.materials[1].coldReference = { rhoGcc: 1.05, Te0: q(0.1, "eV"), Ti0: q(0.1, "eV"), P0: q(0, "GPa"), K0: q(5.8, "GPa") };
  f.numerics.floors.TeFloorEV = 0.1;
  f.numerics.floors.TiFloorEV = 0.1;
  f.output.plotEveryS = q(20, "ps");
  recommendedMesh(f, "coldEquilibriumLayers");
  return f;
}

/** Shock driven by a constant 1 Mbar pressure on the outer face of an ideal-gas slab (hydro
 *  only, 1T): the shock speed and the post-shock state have the exact Rankine-Hugoniot values. */
export function presetPressureShock(): FormState {
  const f = defaultFormState();
  common(f, "pressure_driven_shock", "planar", 5.0);
  f.main.temperatureModel = "1T";
  f.mesh.rMax = um(100);
  f.materials = [idealMaterial("CH", 6.5, 3.5)];
  f.geometry.regions = [region("CH", 100, 1.05, 1e-3)];
  f.hydro.enabled = true;
  f.hydro.boundary1d = "pressure";
  f.hydro.boundaryPressure = { mode: "constant", value: q(1, "Mbar"), points: [{ t: 0, v: 1 }, { t: 5, v: 1 }] };
  f.conduction.enabled = false;
  f.numerics.floors.TeFloorEV = 1e-3;
  f.numerics.floors.TiFloorEV = 1e-3;
  f.output.plotEveryS = q(100, "ps");
  f.mesh.grid1d = "layers";
  f.mesh.layerZoning = [layer({ cells: 400, spacing: "width" })];
  return f;
}

export interface Preset1d {
  id: string;
  build: () => FormState;
  category: "basic" | "option";
  /** TMAT-H5 tables the preset needs on the server (not in the beta distribution). */
  tables: string[];
  /** The run takes hours on one GPU (the card says so). */
  heavy?: boolean;
}

export const PRESETS_1D: Preset1d[] = [
  { id: "blank", build: presetBlank, category: "basic", tables: [] },
  { id: "pressureShock", build: presetPressureShock, category: "basic", tables: [] },
  { id: "marshakWave", build: presetMarshakWave, category: "basic", tables: [] },
  { id: "laserFoil", build: presetLaserFoil, category: "basic", tables: [] },
  { id: "laserShell", build: presetLaserShell, category: "basic", tables: [] },
  { id: "indirectCapsule", build: presetIndirectCapsule, category: "basic", tables: [] },
  { id: "snRadiationFoil", build: presetSnRadiationFoil, category: "option", tables: [] },
  { id: "snbFoil", build: presetSnbFoil, category: "option", tables: [] },
  { id: "cbetHotElectrons", build: presetCbetHotElectrons, category: "option", tables: [], heavy: true },
  { id: "burnPusher", build: presetBurnPusher, category: "option", tables: [] },
  { id: "tableRadiationFoil", build: presetTableRadiationFoil, category: "option", tables: ["TMAT-H5/CD.tmat.h5"] },
  {
    id: "coldEquilibriumLayers",
    build: presetColdEquilibriumLayers,
    category: "option",
    tables: ["TMAT-H5/CD.tmat.h5", "TMAT-H5/D2.tmat.h5"],
  },
];
