#pragma once

namespace tenryu::drivers {

// Multigroup (G=8) 1D planar FLD verification gates. Implementations in
// verify_fld_1d_mg_marshak.cpp; reachable standalone via
// tests/test_verify_mg_marshak_gates.cu and (once the dispatch lines land in
// cmd_verify.cpp) via `tenryu verify <name>`.

// Part A — "fld_1d_mg_planar_marshak_spectrum": marshak-driven equilibration
// of a cold optically-thick planar slab; at the plateau every group must
// satisfy E_g = b_g(T_r) * a * T_r^4 against a gate-internal analytic
// Planck-fraction reference (independent of Groups/PlanckTable).
bool run_fld_1d_mg_planar_marshak_spectrum_verify();

// Part B — "fld_1d_mg_planar_freqdep_relaxation": per-group opacity wiring
// check. freq_dep_marshak opacity, quasi-frozen matter, uniform reflecting
// slab: the backward-Euler relaxation of each group measures sigma_g directly
// (one-step inversion) against a closed-form group Planck mean.
bool run_fld_1d_mg_planar_freqdep_relaxation_verify();

// The multigroup-coverage extension: gates through the table_nlte
// coefficient path (compute_nlte_coefficients_cuda_with_pe), driven by the
// committed Kirchhoff-consistent fixture tests/data/ionmix_mg_fld_g4.cn4
// (generated by tools/generate_ionmix_mg_fld.py).

// "fld_1d_mg_nlte_marshak_spectrum": marshak-driven equilibration through
// the NLTE table path; plateau E_g = b_g(T_r) a T_r^4 against the
// gate-internal analytic reference. The fixed point is provably insensitive
// to the Fleck factor (any f > 0) and to sigma_g — this gate verifies the
// table eta/sigma spectrum wiring, not the fleck layout.
bool run_fld_1d_mg_nlte_marshak_spectrum_verify();

// "fld_1d_mg_nlte_fleck_probe": one backward-Euler step with
// max_outer_iterations = 1 measures the CONSUMED Fleck factor per
// (cell, group): f_meas = E1 (1 + w_g) / (w_g B_g), w_g = c sigma_g dt.
// Detects the fleck-array layout mismatch via
// group-independence and cell-uniformity of f_meas, plus agreement with the
// replicated gray-Fleck formula f = 1/(1 + beta c dt sigma_p_em) at z ~ 1.
bool run_fld_1d_mg_nlte_fleck_probe_verify();

// Mission 3: Su & Olson (1999, JQSRT 62:279) picket-fence two-temperature
// non-equilibrium benchmark, DIFFUSION description (paper section 3 /
// Tables 2-3), run through the multigroup FLD path with flux_limiter="none"
// (exact D_g = c/(3 sigma_g)), fixed Planck measures b_g == p_n via
// PlanckTable::build_constant_fractions, Cv = alpha T^3 via per-step host
// updates of state.cv_e, and the g0-only volume source lifted to the p_n
// split by band-swap superposition (the linearized system is linear). The
// reference is a gate-internal semi-analytic evaluator of the paper's
// Eq. (41) k-integral, cross-checked in-gate against transcribed Table 2/3
// anchor values. Case B (w2/w1 = 10) by default; TENRYU_MG_PICKET_CASE=C
// selects the stiffer Case C as a diagnostic.
bool run_fld_1d_mg_picket_fence_suolson_verify();

}  // namespace tenryu::drivers
