# xc0b_z13 — XC-0b conduction-front coefficient probe (TENRYU side).
# Generated by ops/xc/gen_xc0b_decks.py — edit THAT file, not this one.
# Design: docs/design/xc_tenryu_multiife_1d_comparison_design_20260710.md (XC-0b, Add.1.B)
# MULTI pair: ops/xc/cases/xc0b_z13/multi.input
from tenryu_namelist import *

Z_BAR = 13.0
A = 27.0
RHO0 = 3e-05
TE_HOT = 3000.0    # eV, first 10 cells (0.005 cm)
TE_COLD = 1.0
TI0 = 1.0
F_LIM = 0.1

Main(
    name="xc0b_z13",
    dimension="1D_SPH",
    temperature_model="2T",
    t_end=2.5e-09,
    max_steps=5_000_000,
    seed=12345,
    verbosity="quiet",
)

Mesh(r_min=0.0, r_max=0.2, nr=400, grid="uniform", geometry_1d="planar")

Materials(
    materials=[
        Material(
            name="mat",
            A=A,
            Z=Z_BAR,
            eos=dict(model="ideal_gas", ideal_gas=dict(gamma=1.6666666666666667)),
            opacity=dict(model="constant", kappa_a=0.0, kappa_s=0.0, units="cm2_per_g"),
        )
    ],
    zbar=dict(model="fixed", fixed_value=Z_BAR),
)

Geometry(
    volfrac=dict(mat=lambda r: 1.0),
    rho=lambda r: RHO0,
    Te=lambda r: TE_HOT if r < 0.005 else TE_COLD,
    Ti=lambda r: TI0,
    velocity=lambda r: 0.0,
    radiation_field="zero",
)

Numerics(
    dt=dict(initial_s=1.0e-14, max_s=1.2500000000000001e-12, growth_factor=1.1, min_s=1.0e-20),
    hydro=dict(enabled=False, boundary_1d="reflect"),
    conduction=dict(enabled=True, f_lim=F_LIM),
    floors=dict(rho_floor_gcc=1.0e-10, Te_floor_eV=1.0e-3, Ti_floor_eV=1.0e-3),
)

Radiation(enabled=False)
Laser(enabled=False, cbet=dict(enable=False), hot_electron=dict(enable=False))
Burn(enabled=False)

Output(
    directory="./tmp/xc/xc0b_z13/tenryu",
    plot_every=0,
    history_every=0,
    checkpoint_every=0,
    plot_every_s=5e-11,
    history_every_s=5e-11,
    checkpoint_every_s=-1.0,
)

Diagnostics(enabled=True)
