# xc0c_ib_snapshot — XC-0c laser IB deposition snapshot (TENRYU side).
# Generated by ops/xc/gen_xc0c_decks.py — edit THAT file, not this one.
# Design: docs/design/xc_tenryu_multiife_1d_comparison_design_20260710.md (XC-0c, Add.1.D)
# MULTI pair: ops/xc/cases/xc0c_ib_snapshot/multi.input (identical staircase profile).
from tenryu_namelist import *
import bisect

EDGES = [10.0, 10.0015, 10.001625, 10.001750000000001, 10.001875000000002, 10.002000000000002, 10.002125000000003, 10.002250000000004, 10.002375000000004, 10.002500000000005, 10.002625000000005, 10.002750000000006, 10.002875000000007, 10.003000000000007, 10.003125000000008, 10.003250000000008, 10.003375000000009, 10.00350000000001, 10.00362500000001, 10.00375000000001, 10.003875000000011, 10.004000000000012, 10.004125000000013, 10.004250000000013, 10.004375000000014, 10.004500000000014, 10.004625000000015, 10.004750000000016, 10.004875000000016, 10.005000000000017, 10.005125000000017, 10.005250000000018, 10.005375000000019, 10.00550000000002, 10.00562500000002, 10.00575000000002, 10.005875000000021, 10.006000000000022, 10.006125000000022, 10.006250000000023, 10.006375000000023, 10.006500000000024]
RHOS = [0.0454042048359997, 0.04313891160459322, 0.038941744444541376, 0.03515293742882711, 0.03173275947190524, 0.028645345093580424, 0.02585831831791354, 0.023342453164594334, 0.021071367172544136, 0.01902124474190358, 0.017170587393248404, 0.015499988325142362, 0.013991928905939314, 0.012630594965758597, 0.011401710962191069, 0.010292390280725011, 0.009291000100076684, 0.008387039405344457, 0.007571028869779058, 0.006834411450422153, 0.006169462655215649, 0.005569209540603451, 0.005027357590199136, 0.004538224707737295, 0.004096681632129826, 0.0036980981497933803, 0.003338294540206981, 0.0030134977455366853, 0.002720301804702839, 0.002455632136984268, 0.0022167133006216716, 0.0020010398883228597, 0.0018063502544673723, 0.0016306027985024773, 0.0014719545558278865, 0.0013287418716638358, 0.0011994629552402824, 0.0010827621313628157, 0.0009774156242103292, 0.0008823187242871433, 0.0007964742039566274]

def rho_staircase(r):
    i = bisect.bisect_right(EDGES, r) - 1
    i = max(0, min(i, len(RHOS) - 1))
    return RHOS[i]

Main(
    name="xc0c_ib_snapshot",
    dimension="1D_SPH",
    temperature_model="2T",
    t_end=1e-12,
    max_steps=1_000_000,
    seed=12345,
    verbosity="quiet",
)

# quasi-planar shell: spherical geometry at R0=10.0 cm (see module docstring)
Mesh(r_min=10.0, r_max=10.0065, nr=156, grid="uniform", geometry_1d="spherical")

Materials(
    materials=[
        Material(
            name="hyd",
            A=1.0,
            Z=1.0,
            eos=dict(model="ideal_gas", ideal_gas=dict(gamma=1.6666666666666667)),
            opacity=dict(model="constant", kappa_a=0.0, kappa_s=0.0, units="cm2_per_g"),
        )
    ],
    zbar=dict(model="fixed", fixed_value=1.0),
)

Geometry(
    volfrac=dict(hyd=lambda r: 1.0),
    rho=rho_staircase,
    Te=lambda r: 100.0,
    Ti=lambda r: 100.0,
    velocity=lambda r: 0.0,
    radiation_field="zero",
)

Numerics(
    dt=dict(initial_s=1.0e-15, max_s=2e-14, growth_factor=1.2, min_s=1.0e-20),
    hydro=dict(enabled=True, boundary_1d="reflect"),   # motion ~1.4 nm << dx over 1 ps
    conduction=dict(enabled=False),
    floors=dict(rho_floor_gcc=1.0e-10, Te_floor_eV=1.0e-3, Ti_floor_eV=1.0e-3),
)

Radiation(enabled=False)
Laser(
    enabled=True,
    wavelength_nm=351.0,
    mode="radial_absorption_1d",
    beams=[
        LaserBeam(
            name="beam_00",
            direction=(0.0, 0.0, -1.0),
            power=lambda t: 1.2566370614359173e+17,    # W (Beams W_to_erg_per_s=1e7); I = P/(4 pi R0^2) = 1e14 W/cm^2
            profile=dict(model="super_gaussian", w0_um=1000.0, m=2),
        )
    ],
    cbet=dict(enable=False),
    hot_electron=dict(enable=False),
)
Burn(enabled=False)

Output(
    directory="./tmp/xc/xc0c_ib_snapshot/tenryu",
    plot_every=0,
    history_every=0,
    checkpoint_every=0,
    plot_every_s=1e-13,
    history_every_s=1e-13,
    checkpoint_every_s=-1.0,
)

Diagnostics(enabled=True)
