#!/usr/bin/env python3
"""Generate and certify fixed poles for phi1(z) = (exp(z) - 1) / z.

The rational approximation is obtained from the parabolic Hankel contour

    s(u) = mu * (1 + i*u)^2,
    phi1(z) = (1 / (2*pi*i)) * integral exp(s) / (s * (s - z)) ds.

Midpoint quadrature uses u_j = (j + 1/2)h for j = -M, ..., M - 1,
theta_j = s(u_j), W_j = exp(theta_j) * s'(u_j)h / (2*pi*i), and
omega_j = W_j / theta_j.  The locked parameters are M = 16, mu = 6.45,
and h = 0.141; they come from the certified prototype sweep recorded in
docs/design/exp_mg_phi1_20260717.md section 3 on 2026-07-17.

The certificate is the maximum relative error on the 4000-point grid
z = -logspace(-8, 8), the absolute residuals of the three imposed moments,
and the maximum discrepancy between the full conjugate-pair sum and twice
the real part of the upper-half-plane sum.  The required bounds are 5e-14,
1e-14, and 1e-14, respectively.
"""

from pathlib import Path

import numpy as np


def phi1_exact(z: np.ndarray) -> np.ndarray:
    """Evaluate phi1 with a cancellation-safe branch near zero."""
    z = np.asarray(z, dtype=np.float64)
    result = np.empty_like(z)
    small = np.abs(z) < 1.0e-8
    result[small] = 1.0 + z[small] / 2.0
    result[~small] = np.expm1(z[~small]) / z[~small]
    return result


def build(mu: float, h: float, M: int) -> tuple[np.ndarray, np.ndarray]:
    """Build the full conjugate set of contour poles and residues."""
    j = np.arange(-M, M)
    u = (j + 0.5) * h
    s = mu * (1.0 + 1j * u) ** 2
    ds = mu * 2j * (1.0 + 1j * u)
    W = np.exp(s) * ds * h / (2j * np.pi)
    return s, W / s


def moment_correct(theta: np.ndarray, omega: np.ndarray) -> np.ndarray:
    """Apply the minimum-norm projection onto the three moment constraints."""
    A = np.vstack((1.0 / theta, 1.0 / theta**2, np.ones_like(theta)))
    b = np.array((1.0, 0.5, 1.0), dtype=np.complex128)
    r = b - A @ omega
    omega += A.conj().T @ np.linalg.solve(A @ A.conj().T, r)
    return omega


def certify(theta: np.ndarray, omega: np.ndarray) -> dict[str, object]:
    """Measure the grid error, moment residuals, and half-form discrepancy."""
    z = -np.logspace(-8, 8, 4000)
    terms = omega[:, None] / (theta[:, None] - z[None, :])
    full = np.real(np.sum(terms, axis=0))
    exact = phi1_exact(z)
    sup_relative_error = float(np.max(np.abs(full - exact) / np.abs(exact)))

    moment_residuals = np.array(
        (
            abs(np.sum(omega / theta) - 1.0),
            abs(np.sum(omega / theta**2) - 0.5),
            abs(np.sum(omega) - 1.0),
        ),
        dtype=np.float64,
    )

    upper = theta.imag > 0.0
    half = 2.0 * np.real(np.sum(terms[upper], axis=0))
    half_form_error = float(np.max(np.abs(full - half)))
    return {
        "sup_relative_error": sup_relative_error,
        "moment_residuals": moment_residuals,
        "half_form_error": half_form_error,
    }


def emit_header(
    theta_upper: np.ndarray,
    omega_upper: np.ndarray,
    cert: dict[str, object],
) -> None:
    """Emit the certified upper-half-plane poles as a C++ header."""
    order = np.argsort(theta_upper.imag)
    theta_upper = theta_upper[order]
    omega_upper = omega_upper[order]
    moment_residuals = np.asarray(cert["moment_residuals"])

    def array(name: str, values: np.ndarray) -> str:
        body = "\n".join(f"    {v:.17e}," for v in values)
        return f"inline constexpr double {name}[kNPoles] = {{\n{body}\n}};"

    header = f"""// Generated by tools/gen_phi1_poles.py; do not edit.
// Locked contour parameters: M=16, mu=6.45, h=0.141.
// Certificate (2026-07-17): sup relative error = {cert['sup_relative_error']:.17e},
// moment residuals = [{moment_residuals[0]:.17e}, {moment_residuals[1]:.17e},
//                     {moment_residuals[2]:.17e}],
// half-form error = {cert['half_form_error']:.17e}.
// Provenance: docs/design/exp_mg_phi1_20260717.md section 3.
#pragma once

namespace tenryu::radiation::phi1poles {{

inline constexpr int kNPoles = 16;

{array("kThetaRe", theta_upper.real)}

{array("kThetaIm", theta_upper.imag)}

{array("kOmegaRe", omega_upper.real)}

{array("kOmegaIm", omega_upper.imag)}

}}
"""
    Path("src/radiation/phi1_poles.hpp").write_text(header, encoding="utf-8")


def main() -> None:
    """Generate, correct, certify, and emit the locked approximation."""
    theta, omega = build(mu=6.45, h=0.141, M=16)
    omega = moment_correct(theta, omega)
    cert = certify(theta, omega)

    moment_residuals = np.asarray(cert["moment_residuals"])
    assert cert["sup_relative_error"] <= 5.0e-14, cert
    assert np.all(moment_residuals <= 1.0e-14), cert
    assert cert["half_form_error"] <= 1.0e-14, cert

    upper = theta.imag > 0.0
    emit_header(theta[upper], omega[upper], cert)

    print(f"sup relative error: {cert['sup_relative_error']:.17e}")
    print("moment residuals: " + ", ".join(f"{v:.17e}" for v in moment_residuals))
    print(f"half-form error: {cert['half_form_error']:.17e}")


if __name__ == "__main__":
    main()
