# Writes OUTPUT, a header defining TENRYU_SOURCE_REVISION: the first line of the
# file SOURCE_REVISION at the top of the source tree (tools/beta_export.sh writes
# it into an exported tree), else the git commit of the source tree with
# "+modified" when tracked files differ from it, else "unknown". Run at every
# build (src/core/CMakeLists.txt); the header is rewritten only when its content
# changes, so only version.cpp recompiles when the revision moves.
# Usage: cmake -DSOURCE_DIR=<dir> -DOUTPUT=<header> -P SourceRevision.cmake
set(revision "unknown")
if(EXISTS "${SOURCE_DIR}/SOURCE_REVISION")
  file(STRINGS "${SOURCE_DIR}/SOURCE_REVISION" lines LIMIT_COUNT 1)
  if(lines)
    list(GET lines 0 revision)
  endif()
else()
  find_package(Git QUIET)
  set(top "")
  if(GIT_FOUND)
    # Only a tree that is itself a git work tree: not a copy inside another repository.
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --show-toplevel
      OUTPUT_VARIABLE top
      RESULT_VARIABLE rc_top
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)
    if(rc_top EQUAL 0)
      get_filename_component(top "${top}" REALPATH)
    else()
      set(top "")
    endif()
  endif()
  get_filename_component(source_real "${SOURCE_DIR}" REALPATH)
  if(NOT top STREQUAL "" AND top STREQUAL source_real)
    execute_process(
      COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" rev-parse --short=9 HEAD
      OUTPUT_VARIABLE sha
      RESULT_VARIABLE rc
      OUTPUT_STRIP_TRAILING_WHITESPACE
      ERROR_QUIET)
    if(rc EQUAL 0 AND NOT sha STREQUAL "")
      set(revision "${sha}")
      execute_process(
        COMMAND "${GIT_EXECUTABLE}" -C "${SOURCE_DIR}" status --porcelain --untracked-files=no
        OUTPUT_VARIABLE changes
        RESULT_VARIABLE rc_status
        ERROR_QUIET)
      if(rc_status EQUAL 0 AND NOT changes STREQUAL "")
        string(APPEND revision "+modified")
      endif()
    endif()
  endif()
endif()
# Only characters that are safe inside a C string literal.
string(REGEX REPLACE "[^A-Za-z0-9@+._:/-]" "" revision "${revision}")
if(revision STREQUAL "")
  set(revision "unknown")
endif()
set(content "#pragma once\n// Generated by cmake/SourceRevision.cmake.\n#define TENRYU_SOURCE_REVISION \"${revision}\"\n")
set(previous "")
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" previous)
endif()
if(NOT previous STREQUAL content)
  file(WRITE "${OUTPUT}" "${content}")
endif()
