// Retired with the Monte Carlo radiation on 2026-09-29: the entry of src/radiation/nlte_coeffs.cu (and its declaration
// in nlte_coeffs.cuh) that only the IMC/DDMC path called, as it was at 5bc8f6ce3. Not built; the implementation it
// forwards to, compute_nlte_coefficients_cuda_impl, stayed in nlte_coeffs.cu with the entries of the FLD and S_N.

#include "radiation/nlte_coeffs.cuh"

namespace tenryu::radiation {

/// GPU computation of NLTE radiation coefficients using separate emissivity.
/// Outputs are written directly to device buffers owned by the caller.
NlteCoeffsDeviceResult compute_nlte_coefficients_cuda(
    const double* d_rho,
    const double* d_Te,
    const double* d_zbar,
    const double* d_cv_e,
    const std::uint8_t* cell_is_void_host,
    std::size_t cell_is_void_size,
    const materials::IonmixOpacityDeviceView& table_view,
    const PlanckTableDeviceView& planck_view,
    int n_cells, int n_groups,
    double dt, double A, double alpha,
    double f_min, double f_max,
    double fd_delta_rel, double fd_abs_min,
    double sigma_cap, double cv_e_override,
    double temperature_floor_eV,
    double gamma_m1, bool linearized_planck,
    bool use_freeze_opacity, bool corrected_fleck,
    double* d_f,
    double* d_sigma_pa, double* d_sigma_R,
    double* d_sigma_a_eff, double* d_sigma_s_eff,
    double* d_eta_cdf,
    double* d_eta,
    double* d_lambda_raw,
    cudaStream_t stream,
    bool low_density_extrap = false,
    const int* cell_material_index = nullptr,
    int material_filter = -1);

NlteCoeffsDeviceResult compute_nlte_coefficients_cuda(
    const double* d_rho,
    const double* d_Te,
    const double* d_zbar,
    const double* d_cv_e,
    const std::uint8_t* cell_is_void_host,
    std::size_t cell_is_void_size,
    const materials::IonmixOpacityDeviceView& table_view,
    const PlanckTableDeviceView& planck_view,
    int n_cells,
    int n_groups,
    double dt,
    double A,
    double alpha,
    double f_min,
    double f_max,
    double fd_delta_rel,
    double fd_abs_min,
    double sigma_cap,
    double cv_e_override,
    double temperature_floor_eV,
    double gamma_m1,
    bool linearized_planck,
    bool use_freeze_opacity,
    bool corrected_fleck,
    double* d_f,
    double* d_sigma_pa,
    double* d_sigma_R,
    double* d_sigma_a_eff,
    double* d_sigma_s_eff,
    double* d_eta_cdf,
    double* d_eta,
    double* d_sigma_p_em,
    cudaStream_t stream,
    bool low_density_extrap,
    const int* cell_material_index,
    int material_filter) {
  return compute_nlte_coefficients_cuda_impl(
      d_rho,
      d_Te,
      d_zbar,
      d_cv_e,
      cell_is_void_host,
      cell_is_void_size,
      table_view,
      planck_view,
      n_cells,
      n_groups,
      dt,
      A,
      alpha,
      f_min,
      f_max,
      fd_delta_rel,
      fd_abs_min,
      sigma_cap,
      cv_e_override,
      temperature_floor_eV,
      gamma_m1,
      linearized_planck,
      use_freeze_opacity,
      corrected_fleck,
      d_f,
      d_sigma_pa,
      nullptr,
      d_sigma_R,
      d_sigma_a_eff,
      d_sigma_s_eff,
      d_eta_cdf,
      d_eta,
      d_sigma_p_em,
      false,
      stream,
      low_density_extrap,
      nullptr,
      false,
      cell_material_index,
      material_filter);
}

}  // namespace tenryu::radiation
